# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: echo 'Success'
